version: '3.8'
services:
  masstransit-posbooks:
    image: masstransit/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "posServer2024!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
  
  posbooks-producer:
    image: posbooksproducer
    environment:
      - "ConnectionStrings__SQLConnection=Server=sqlserver;Database=PosBooksProducer;User Id=sa;Password=posServer2024!;TrustServerCertificate=True;"
      - "AllowedHosts=*"
      - "MassTransit__NomeFilaAlugarLivro=PosBooksProdutorAlugarLivro"
      - "MassTransit__NomeFilaDevolverLivro=PosBooksProdutorDevolverLivro"
      - "MassTransit__Servidor=masstransit-posbooks"
      - "MassTransit__Usuario=guest"
      - "MassTransit__Senha=guest"
    ports:
      - "5000:8080"

  posbooks-consumer:
    image: posbooksconsumer
    environment:
      - "Logging__LogLevel__Default=Information"
      - "Logging__LogLevel__Microsoft.Hosting.Lifetime=Information"
      - "ConnectionStrings__SQLConnection=Server=sqlserver;Database=PosBooksConsumer;User Id=sa;Password=posServer2024!;TrustServerCertificate=True;"
      - "MassTransit__NomeFilaAlugarLivro=PosBooksProdutorAlugarLivro"
      - "MassTransit__PosBooksProdutorDevolverLivro=PosBooksProdutorDevolverLivro"
      - "MassTransit__Servidor=masstransit-posbooks"
      - "MassTransit__Usuario=guest"
      - "MassTransit__Senha=guest"
      - "Email__ServidorSMTP=smtp.gmail.com"
      - "Email__PortaSMTP=587"
      - "Email__Usuario=andbat2122@gmail.com"
      - "Email__Senha=rrowzxysyrexheih"