// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PosBooks.Model;

#nullable disable

namespace PosBooks.Migrations
{
    [DbContext(typeof(PosBookContext))]
    [Migration("20240119024303_migration_inicial")]
    partial class migrationinicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PosBooksCore.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Jorge Amado",
                            Publisher = "Cia das Letras",
                            Title = "Capitães da Areia",
                            Year = 2010
                        },
                        new
                        {
                            Id = 2,
                            Author = "Octavia E. Butler",
                            Publisher = "Morro Branco",
                            Title = "Kindred",
                            Year = 2019
                        },
                        new
                        {
                            Id = 3,
                            Author = "Marília de Camargo César",
                            Publisher = "Thomas Nelson Brasil",
                            Title = "O grito de Eva",
                            Year = 2021
                        },
                        new
                        {
                            Id = 4,
                            Author = "CS Lewis",
                            Publisher = "Harper Collins",
                            Title = "As Crônicas de Nárnia",
                            Year = 2023
                        },
                        new
                        {
                            Id = 5,
                            Author = "Louise Greig",
                            Publisher = "Harper Collins",
                            Title = "O Pequeno Príncipe",
                            Year = 2023
                        },
                        new
                        {
                            Id = 6,
                            Author = "JRR Tokien",
                            Publisher = "Rocco",
                            Title = "O Hobbit",
                            Year = 2019
                        },
                        new
                        {
                            Id = 7,
                            Author = "Margaret Atwood",
                            Publisher = "Cia das Letras",
                            Title = "O conto da aia",
                            Year = 2017
                        },
                        new
                        {
                            Id = 8,
                            Author = "Isaac Asimov",
                            Publisher = "Aleph",
                            Title = "Fundação",
                            Year = 2009
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
