// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PosBooksConsumer.Models;

#nullable disable

namespace PosBooksConsumer.Migrations
{
    [DbContext(typeof(PBCContext))]
    [Migration("20240115200946_CreateDatabase")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("PosBooksConsumer.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RenterEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RenterEmail");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Jorge Amado",
                            Publisher = "Cia das Letras",
                            Title = "Capitães da Areia",
                            Year = 2010
                        },
                        new
                        {
                            Id = 2,
                            Author = "Octavia E. Butler",
                            Publisher = "Morro Branco",
                            Title = "Kindred",
                            Year = 2019
                        },
                        new
                        {
                            Id = 3,
                            Author = "Marília de Camargo César",
                            Publisher = "Thomas Nelson Brasil",
                            Title = "O grito de Eva",
                            Year = 2021
                        },
                        new
                        {
                            Id = 4,
                            Author = "CS Lewis",
                            Publisher = "Harper Collins",
                            Title = "As Crônicas de Nárnia",
                            Year = 2023
                        },
                        new
                        {
                            Id = 5,
                            Author = "Louise Greig",
                            Publisher = "Harper Collins",
                            Title = "O Pequeno Príncipe",
                            Year = 2023
                        },
                        new
                        {
                            Id = 6,
                            Author = "JRR Tokien",
                            Publisher = "Rocco",
                            Title = "O Hobbit",
                            Year = 2019
                        },
                        new
                        {
                            Id = 7,
                            Author = "Margaret Atwood",
                            Publisher = "Cia das Letras",
                            Title = "O conto da aia",
                            Year = 2017
                        },
                        new
                        {
                            Id = 8,
                            Author = "Isaac Asimov",
                            Publisher = "Aleph",
                            Title = "Fundação",
                            Year = 2009
                        });
                });

            modelBuilder.Entity("PosBooksConsumer.Models.Client", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Email");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("PosBooksConsumer.Models.WaitList", b =>
                {
                    b.Property<int>("BookRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequesterEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasIndex("BookRequestId");

                    b.HasIndex("RequesterEmail");

                    b.ToTable("WaitList");
                });

            modelBuilder.Entity("PosBooksConsumer.Models.Book", b =>
                {
                    b.HasOne("PosBooksConsumer.Models.Client", "Renter")
                        .WithMany()
                        .HasForeignKey("RenterEmail");

                    b.Navigation("Renter");
                });

            modelBuilder.Entity("PosBooksConsumer.Models.WaitList", b =>
                {
                    b.HasOne("PosBooksConsumer.Models.Book", "BookRequest")
                        .WithMany()
                        .HasForeignKey("BookRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PosBooksConsumer.Models.Client", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterEmail")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookRequest");

                    b.Navigation("Requester");
                });
#pragma warning restore 612, 618
        }
    }
}
